exports.CONNECT = "CONNECT";
exports.MESSAGE_RECEIVED = "MESSAGE_RECEIVED";
exports.SEND_MESSAGE = "SEND_MESSAGE";
exports.GET_MESSGAES = "GET_MESSAGES";
exports.MESSAGES = "MESSAGES";
exports.ONLINE_FRIEND = "ONLINE_FRIEND";